server:
  port: 8082
spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8090
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
  swagger:
    package: com.hmall.cart.controller
