server:
  port: 8083
spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8090
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-user
  swagger:
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
